The United States had a budget surplus of a total of $423 billion for the three years of 1998, 1999, and 2000.
This surplus was created by a combination of a balanced budget package and an exceptional economy.
Strong growth, low inflation, a strong job market, increased productivity, and increased consumer spending characterized the economy.
In the year 2000, expectations were high for future budget surpluses.
The White House forecast a surplus of $4 to $4.4 trillion over the next 15 years.
Congress was predicting a surplus of $2.6 to $2.9 trillion over the next 10 years.
There was a large disparity between the Democrats and Republicans on what to do with this surplus.
The Democrats wanted to spend the money and have only limited tax cuts.
They wanted to shore up social security and Medicare and reduce the Federal debt with a goal of no debt by 2012.
They wanted to spend money on job training, education, defense--including a pay raise for military personnel, medical research, improved health care, school construction, and assistance to the unemployed and those with low incomes.
The Republicans considered the surplus an overpayment by American taxpayers and primarily sought to cut taxes, targeting $800 billion in cuts over the next 10 years.
They did agree on more spending for social security, instituting a prescription drug benefit for Medicare, and some reduction of the Federal debt with a target of no debt by 2016.
