The US Federal budget surpluses achieved in the late 1990s were the result of fiscal discipline imposed after the huge deficits of the previous decade.
Treasury Secretary Robert Rubin is credited with strong fiscal management and Federal Reserve Chairman Alan Greenspan kept interest rates low.
A strong job market, low inflation and high productivity were factors boosting the surplus.
Wall Street was booming and investors were getting richer and increasing the tax base.
It appeared to many economists that an era of budget surpluses was at hand and surpluses could be expected 15 years ahead.
The Congressional Budget Office in 1995 had projected deficits ten years ahead but by 1998 was predicting a $100 billion surplus for 2005.
But they had projected $100-200 billion deficit for 1997 that turned into a $100-200 billion surplus thus casting doubt on its forecasting ability.
The existence of a surplus naturally had politicians proposing ways to spend it.
The Clinton Administration called for Social Security and Medicaid funding, retirement saving accounts and military readiness.
Many liberals wanted more spending on education, basic technology, medical research and transportation.
Chairman Greenspan initially signed onto Social Security finding but later argued for debt reduction.
The Republicans all called for tax cuts.
One prominent House Republican argued that all taxes, except for the payroll tax, should be cut.
Chairman Greenspan said that a tax cut would be better suited for a time when the economy has turned down.
