Perjury is a false statement knowingly made in a court proceeding about some matter material to the issue or point in question.
The prosecution must demonstrate that a person knew that the statement was inaccurate and intended to make a false statement.
A 1972 Supreme Court decision made it clear that an unresponsive or misleading statement, even a half-truth, is not enough for conviction.
Perjury is a both a criminal and civil federal offense, but perjury convictions are more prevalent in state courts.
From 1992 to 1998 there were 700 federal perjury prosecutions and 16,000 perjury prosecutions in California.
In 1997 federal perjury cases were.1% of the total prosecutions and California perjury prosecutions were 1%.
Perjury convictions often accompany other charges or are pursued because other suspected crimes cannot be prosecuted successfully.
For example, Alger Hiss, a suspected spy, served 3 years for perjury.
Federal punishment is a fine, prison for up to 5 years, or both.
Actual sentences have range from public service to 60 days to 5 years in jail.
In 1997 the average sentence for a federal conviction was 27 months.
Two federal judges have been impeached and removed from office for lying.
A British politician was completely ruined for lying and a British killer, initially found not guilty but who later confessed, received 6 years for lying.
President Clinton was impeached but not convicted by Congress, but was later convicted in civil court.
He had to pay court costs and faced disbarment .
