Although there are gradations of emphasis, two basic perspectives are at the core of the debate over teaching of evolution, creation science or intelligent design in public school science classes.
Scientists, science teachers and their supporters see evolution as one of five unifying concepts linking all scientific disciplines.
To ignore it is to ignore science and relegate students to an inferior education and uncertain future.
They see creationism as a literal reading of Genesis clearly contradicted by science and intelligent design as little more than substitution of "intelligent designer" for "God" in the Genesis account, following court decisions against teaching creationism as science.
Supporters of creationism, creation science, and intelligent design are primarily fundamentalist Christians who have faith in the literal truth of the Bible.
They dispute the validity of evolutionary theory arguing that there are holes in it.
Intelligent design avoids mention of God saying the complexity of the design of the cosmos requires an intelligent designer.
Some condemn the teaching of evolution as a form of secular humanism undermining religions, social and cultural values.
Rep. Tom DeLay put the blame for the tragic Columbine High massacre on teaching children "that they are nothing but glorified apes who are evolutionized out of some primordial soup of mud." In 1999 a poll showed 83% of Americans favoring teaching evolution in the public schools and 68% thinking one can both believe in evolution and that God created humans and guided their development.
