Obsessive-compulsive disorder (OCD) is characterized by senseless repetitive thoughts and behaviors, which typically deal with grooming, contamination, or danger.
Sufferers may wash their hands continually or repeatedly check their appearance in mirrors.
They are nervous and frequently fidget and twitch.
The diagnostic manual of the American Psychiatric Association states sufferers are preoccupied with details, rules, order, or schedules to the extent that the point of the activity is lost.
They show perfectionism that interferes with task completion.
They are over-conscientious and inflexible.
They are devoted to work and productivity to the exclusion of leisure activities and friendships.
They may be unable to discard worthless objects.
OCD is one of a related group of anxiety disorders.
Other illnesses in this group include panic attacks, post-traumatic stress, generalized anxiety disorders, phobias, animal hoarding, and body dysmorphic disorder.
OCD victims may also suffer from anorexia and depression.
There is some evidence that these disorders, along with tinnitus and Parkinson's disease, stem from the same brain defect--a decoupling of two brain regions that normally work in synchrony.
If true, implanting electrodes may provide relief.
Treatment consists of medications, psychotherapy, or a combination of the two.
Effective drugs include serotonin reuptake inhibitors such as flouxetine (Prozac), sertarline (Zoloft), clomipramine (Anafranil), and fluvoxamine (Luvox).
Each has varying effectiveness and side effects.
Several are effective with children who have OCD.
The most successful psychotherapy appears to be cognitive-behavioral therapy, where the patient learns to moderate moods by manipulating his thoughts in a certain direction.
