The only supersonic passenger plane--the Concorde--crashed on July 25, 2000, killing all 109 on board and 4 on the ground.
Developed by the French and British under a 1962 agreement, it made its first passenger flight in 1976.
Twenty planes were built and 13 were still flying in 2000.
A roundtrip flight cost $10,000.
The plane had 100 seats and flew 1,300 mph at 60,000 feet.
It took less that 4 hours to cross the Atlantic carrying the rich, the famous, and business people.
It started out a technological miracle, but became an economic disaster and an elegant cultural artifact of the 20th Century.
The crash was caused by a piece of metal falling off of a Continental DC10 that used the runway before the Concorde.
The metal cut the Concorde's tire and flying rubber damaged the engines causing a fuel leak that burst into flame, too late to abort.
It crashed into a small hotel.
All the bodies were found and identified and the wreckage was moved to be reassembled.
The French opened an inquiry to place blame, hearing from 295 witnesses.
Almost all of the passengers were Germans going to New York.
Air France paid each family $20,000 to cover immediate expenses.
Memorial services were held in Paris, in Cologne, Germany, and later at the crash site.
Air France immediately grounded its fleet and British Airways stopped flights on August 15.
Air France was investigating modifications to insure safety and sued Continental on September 27.
