The supersonic transport Concorde was a joint Anglo-French development begun in 1962.
The size and design of the Concorde allowed for only 100 passenger seats.
Just twenty of the transports were built and only British Airways and Air France flew them.
The first passenger flight was in January 1976.
A nine person crew provided luxury service and gourmet food and drink.
The Concorde could make the flight between New York and London or Paris in less than four hours and once set a record by doing it in slightly less than three.
The Concorde could only fly over ocean areas because of the problems sonic booms would cause over land areas.
Travel on the Concorde appealed to the "rich and famous" and to businessmen on a tight schedule.
Low passenger capacity, limitations on routes and high costs prevented the Concorde from ever becoming a significant factor in aviation.
The Concorde had an impeccable safety record until July 25, 2000, when Air France charter flight AF4590 crashed less than two minutes after taking off from Charles de Gaulle Airport.
All 109 aboard the aircraft, most of whom were German tourists, and four persons at the crash site died.
Air France and British Airways immediately cancelled all Concorde flights but British Airways resumed them the next day.
Indications are that a piece of scrap metal on the runway punctured a tire, chunks of which ruptured a fuel tank next to two engines which ignited escaping fuel.
