Stephen Lawrence, a promising 18 year-old son of Jamaican immigrant parents, was stabbed to death at a London bus stop in April 1993.
He was attacked by five white youths with a history of race baiting.
Three of the alleged killers were tried and acquitted.
Charges against the other two were dropped for insufficient evidence.
Police racism is believed to have led to poor handling of the case against the five.
London's Metropolitan Police, according to a later government report were found to be "riven with pernicious and institutionalized racism".
Even before the report was issued, public confidence in the police had fallen.
The Lawrence murder and its aftermath served to question the common belief in Britain that its race relations are better than they are in the United States.
Britain overall is 94% white and has never had a civil rights movement.
In London, 20% of the population is minority but are only 2.3% of the police force.
The Labor government of Tony Blair promised a radical overhaul of race discrimination laws and hoped that in ten years every police force in England and Wales would reflect the racial make-up of the area it served.
Seven years after the Lawrence murder, police were cracking down on racist crime in London under an operation named Athena.
In 2000, Price Charles launched a scholarship in memory of Lawrence to open up architecture, Lawrence's chosen field of study, to ethnic minorities.
The Prince also expressed his deepest sympathy to Stephen's parents.
