The Hague Convention on Intercountry Adoptions establishes safeguards so that international adoptions meet global standards to protect children.
The United States has ratified the Convention, although some US legislators proposed implementing legislation that would preclude homosexuals and others with "promiscuous lifestyles" from adopting children.
Russia has replaced China as the nation providing most children for adoption in the US and those two countries have been amending their laws to prevent abuses in adoptions.
In many cases those laws specify a one-child adoption limit and who can negotiate for the adoption.
International adoption by US families notably traces to adoption of Korean orphans after the Koran War.
Many US couples look to international adoptions because of a smaller and smaller supply of white American-born infants and the expense in competing for them.
In many foreign countries the supply of babies exceeds the demand.
Race is a factor in adoptions; many white couples are unlikely to adopt a black infant.
US families rarely adopt children from Africa.
The first children adopted from foreign countries had only their adoptive parents for support and often suffered from discrimination.
More recently adoptive parents are screened for cultural sensitivity so that the adopted children are not shut off from the national and ethnic heritage.
Now more parents are seeking guidance on the issue of race in their families.
Cultural awareness events and support groups are being formed in the US.
