Bombings of US Embassies in Kenya and Tanzania in August 1998 killed 224 and injured 5,000 in Kenya and killed 11 and injured 70 in Tanzania.
The near simultaneity of the attacks indicated careful planning and close coordination by the perpetrators.
Planning for the attack took three months and was carried out by an Egyptian Islamic Jihad group linked to Osama bin Laden.
Some of the bombers entered Kenya through Somali and Rwanda.
Explosives originated in the Middle East and were brought by sea to the Comoros Islands then to Tanzania.
Those to be used in Kenya then went by road to Nairobi.
Part of the bomb used at the embassy in Dar Es Salaam was assembled at Tomy Spaares Manufactures Ltd, a metal-working shop.
A refrigerator truck transported the bomb that was detonated at the embassy.
The bomb that destroyed the embassy in Nairobi was built at a house rented on the outskirts of that city by a man identified as Haroun Fazil.
Fazil is alleged to have driven a white pickup truck to the embassy on the day of the bombing to lead the vehicle carrying the bomb.
He and his associates are believed members of al-Qaeda.
In all, 17 men have been indicted in New York on charges related to the bombings.
Five of them who are still at large are accused of conspiring with Osama bin Laden.
