On August 7, 1998, coordinated bombings blasted the US embassies in Kenya and Tanzania.
More than 250 people were killed and over 5,000 injured, most of them Kenyans and Tanzanians.
Twelve Americans were killed.
Shortly, thereafter, US federal law enforcement officials tentatively linked Osama bin Laden to the two bombings.
Cairo-based, Islamic Jihad, financed by bin Laden was also suspected.
Some suspects were arrested within the two first weeks after the blasts, Khalid Mohammed accused of hurling a grenade at security guards among them.
Confessions by the early arrested suspects confirmed suspicions of the link with bin Laden.
Two suspects, Khalid Salim and Mohammed Saddiq Odeh, were flown to the US for trial.
Local police arrested many other suspects.
Police were soon to determine the materials and methods involved in the bombing plot.
The bomb ingredients originated in the Middle East, were transferred by sea via the Comoro Islands to Tanzania.
The bomb was assembled at the home of Haroun Fazil, of Comoro.
The explosive device was then attached to a vehicle in a metal workshop owned by prominent Dar Es Salaam businessman, Tony Lyimo.
The bomb, packed with batteries and oxygen tanks to make it more explosive, was carried into the compound by refrigerator truck.
Arrested suspect, Mustafa Mahmoud Said Ahmed, gave details of both bombing.
In Kenya, the bomb was carried in a white Suzuki Sumurai.
He had been warning US officials for months before the attack, saying that three vehicles would be used in an attack.
