Bookselling in the United States changed dramatically in the 1990s.
Independent booksellers have been the hardest hit by the changes.
In 1991, the independents claimed nearly a third of adult book purchases but six years later their market share was nearly cut in half, down to 17%.
The American Booksellers Association (ABA) that represents the independents saw its membership drop from 5,200 to less than 3,500.
Large chain booksellers like Barnes & Noble and Borders did increase market share by 3% during this same period but they too faced increasing challenges from price clubs and especially from online booksellers such as Amazon.
The ABA was formed to represent and promote the independent booksellers.
They filed suit against Barnes&Noble when it made a bid to acquire the leading book wholesaler Ingram Book Group.
That bid was later dropped because of opposition from the Federal Trade Commission but had it gone through, Barnes&Noble could have optimized its own position by preferential channeling of book distribution through its stores to the detriment of the independents.
Online bookselling continued to increase its share of the book market.
The chains and independents have also established online sites.
Barnes&Noble established an online venture that in at least one year lost money.
The Independents also established its own national online store, Book Sense, to stave off fierce competition from Amazon.com and Barnesandnoble.com.
They also formed Bookfinder.com to permit online browsing of inventories of thousands of independent bookshops.
