Computer viruses have turned up in just about every part of the world.
Viruses and "worms" come with names like Happy 99, Melissa, Chernobyl, Killer C, White Lion, and Love Bug.
Damage to commercial systems and thousands of personal computers from viruses has been extensive and has run into billions of dollars.
A virus will generally erase a computer's hard drive and prevent the machine from being restarted.
A worm does no direct damage to the computer but insinuates itself among programs and attaches itself to every message sent.
Worms and viruses are mostly spread by emails and attachments thereto.
The emails that carry the infecting viruses and worms are in a Microsoft Word document and the systems that are affected by the viruses and worms are Word 95, 97, 98, 2000, Windows NT, Outlook, and Outlook Express.
An otherwise useful feature of Microsoft Word is that it enables macro programs, scripts that trigger actions by a host computer.
This feature has been exploited by hackers to introduce Worms.
David Smith of Aberdeen, NJ, was arrested for originating the Melissa worm.
The Chernobyl virus is known in Taiwan as the CIH virus for the initials of its creator Chen Ing-hau.
The Love Bug worm was attributed to a Philippine couple, Rommel Lamores and Irene de Guzman.
A later, more deadly version of the Love Bug may have originated in Israel.
The Explore worm had also originated in Israel.
