Elian Gonzales, 6, was rescued at sea on November 25, 1999.
He, his mother, and 12 others had fled Cuba in a motorboat that capsized.
Only two survived.
Elian's great-uncle in Florida was granted temporary custody, but his father demanded his return to Cuba.
The great-uncle applied for asylum for Elian, but the Immigration and Naturalization Service, in accordance with US and international law, ruled that Elian belonged with his father and should be returned to Cuba.
Elian became a symbol of the continuing struggle between Castro and the US Cuban-exile community.
Both sides sought popular support and staged demonstrations and strikes.
Other communist countries backed Castro.
Elian's Cuban grandmothers visited him in Florida in January and, in April, his father arrived in Washington.
Congress made several attempts to become involved--offering Elian and his father asylum and discussing an act of Congress.
When the great-uncle refused to relinquish custody, Elian was seized by federal agents and taken to his father, resulting in riots in Miami.
The great-uncle fought through the Federal courts to retain custody.
He filed a federal lawsuit, which was dismissed in March, but Elian was enjoined from leaving the United States during the appeal process.
On June 1 the appeal was denied and this denial was upheld on June 23.
On June 28 the Supreme Court refused to review the case or extend the injunction.
Elian and his father returned to Cuba on a chartered plane that day, later meeting with Castro.
