The seat belt is the most effective automobile safety device.
Getting people to use them remains a problem, which has been addressed by installing use-sensors and enacting laws to stop and fine non-users.
Airbags should protect, but not injure, the drivers and front seat passengers.
Devices were installed to prevent their deployment when passengers are too small.
Side airbags or curtains, again that can be deactivated, are being installed to prevent injuries in side collusions or rollovers.
Additional interior cushioning is used to avoid head injuries and having the backrest and head restraint shift backward in a rear end collusion can provide whiplash protection.
Infant car seats, child restraints, and booster seats, all placed in the back seat, are the keys to protecting children in a crash.
Enforcing their use and programs to educate parents on the correct use and installation are key.
Crash tests, finally beginning in China, should include child dummies in the back seat.
Engineers are seeking ways to avoid the accident in the first place.
Anti-lock brakes, computerized stability and traction control, all-wheel drive, low-tire-pressure detectors, reverse sensing systems, better suspension and handling, and blue-tint headlights all contribute to this end.
In addition, states are enacting graduated licensing laws to limit new drivers until they gain experience.
Finally the installation and analysis of "black boxes" that record data in the last seconds before a crash will allow engineers to better understand crashes and the causes of injuries.
