Vladimir Putin was born in St. Petersburg in 1952.
He graduated from Leningrad State University and began a career as a spy with the KGB.
After serving 15 years, many of those in Germany, Putin returned to St. Petersburg and began working for the local government.
He was aide to the Mayor from 1991 to 1996.
He then moved with his wife and two daughters to Moscow, later becoming director of the Federal Security Service.
In August 1999 Boris Yeltsin named Putin acting Prime Minister and announced that he wanted Putin to succeed him as President in the election scheduled for the summer of 2000.
Suddenly at the end of December, Yeltsin resigned and named Putin acting President.
This resignation moved the election to March 2000.
Putin ran a slick campaign, reaching out to the various interest groups, raising pensions, and promising to raise wages, improve education, increase conventional defense spending, and fight crime.
He was popular with many because of his tough stand in the war in Chechnya.
Two weeks before the election a book of interviews was published aimed at humanizing his image.
His main opponent was the chief of the Communist Party.
Putin won the March 26 election with 53% of the vote.
After his election he moved very cautiously.
He did not reveal his economic plan, staying intentionally vague.
He also did not replace the Minister of Defense.
He traveled only to Belarus, the Ukraine, and the United Kingdom.
He was sworn in on May 5.
