HIV/AIDS is a major problem in Kenya where, in 1999, 1.9 million people were afflicted.
The nation has a National AIDs and STI (sexuality transmitted infection) Program.
The World Bank provided $46 million for a program to enhance awareness of this scourge.
The UN Children's Fund declared war on AIDS and urged churches to join.
Money was sought for treatment and education initiatives.
Free condom dispensers were installed in public areas.
In 2000, public policy was being reviewed to address environmental, sanitary, and housing problems and "loopholes" that encouraged the spread of this disease.
Malaria also is a major health problem with 3 million cases in Africa each year.
The World Health Organization was helping with the fight.
Anti-malaria campaigns are run and drugs are distributed.
Kenya was bringing in sulphur-based drugs since some strains of the parasite were chloroquin resistant.
Other water borne diseases include typhoid, cholera, dysentery, and hemorrhagic fever.
Kenyans are urged to boil their water.
The Japan International Agency was providing money for research and control of infectious diseases.
The population is less able to fight these diseases because of malnutrition.
Eight percent of children die by age 5 because of malnutrition.
Kenya and the UN Food and Agriculture Organization sponsored a workshop in 1999.
The nation has greatly increased the number of heart specialists who treat coronary artery disease, which is afflicting the more affluent; rheumatic heart disease in the poor; and congenital defects.
Used clothing must be certified safe to prevent fungal diseases.
