Residents of Kenya continue to be plagued by the diseases they have struggled with for many years: malaria, typhoid dysentery, tuberculosis, cholera, diarrhea, Rift Valley fever and malnutrition.
Heart attacks are on the rise.
The greatest threat to life and health, however, has been the spread of HIV/AIDS.
The more "traditional" diseases continue to cause death and lingering sickness but the impact of HIV/AIDS has raised Kenyan misery to new heights.
It is reported that 500 persons die from HIV/AIDS each day.
HIV/AIDS has created a million orphans in that country.
The advance of this dreaded disease is expected to lower a Kenyan's life expectancy that stands as 58 years in 1998 to only 42 years by 2010.
The Gross Domestic Product has lost 14.5%.
One of every ten children born in Kenya now dies from a preventable disease before the age of five.
The children die mainly from malaria, diarrhea, vomiting and malnutrition.
Some positive steps are being taken.
In cooperation with several of its African neighbors Kenya is assessing the magnitude of diseases affecting it and nearby countries.
Kenya has increased the number of cardiologists for treating heart disease.
They are providing free condoms to stem the advance of HIV/AIDS.
Anti-malarial drugs are replacing those whose effectiveness has diminished.
Kenya is receiving aid from international organizations like the World Bank and the World Health Organization and from the United States and Japan.
Most of this aid is for combating the spread of HIV/AIDS.
