The West Nile virus was first identified in the United States in the summer of 1999 after birds began dying in and near the Bronx Zoo.
The virus killed 7 and sickened 77 in New York City.
Horses on Long Island also died and afflicted birds were found in New Jersey, Connecticut, and Baltimore.
After the winter, the virus again appeared in New York City, New Jersey, and Connecticut, then in June in Delaware, and in July in Boston.
The first human victim for 2000 was on Staten Island and the virus began spreading into New York State.
Afflicted birds were found in Rhode Island in August and in Baltimore and Philadelphia in September.
Seventeen people contracted the disease, one died.
The virus was expected in Georgia and North Carolina and 17 eastern states were on alert.
The West Nile virus was discovered in 1937 in Uganda and the U.S. strain probably came from Israel.
It is transmitted by mosquitoes, which bite infected birds then spread it to other birds, people and other animals.
Control focused on detection, mosquito elimination, and personal protection.
Detection consisted of testing mosquitoes, dead birds, and people who appeared ill.
"Sentinel" chickens were kept down the east coast and tested weekly.
Insecticides were sprayed over threatened areas and larvacides were placed in water.
People were urged to install window screens, stay inside in the early morning and evening, wear long sleeves and pants, use DEET insect repellent, remove standing water, and keep grass short.
