West Nile virus was first detected in the United States in August 1999.
Discovery of the virus occurred in Uganda in 1937.
For many years, the virus was found only in Africa, parts of Asia and Eastern Europe.
Humans, birds and horses are subject to the disease.
The virus is transmitted by bites from infected mosquitoes.
The disease cannot be contacted person-to-person or by handling birds with the disease or having died from it.
The disease discovered in Queens, New York, may have been brought to the US in infected birds from Israel, since the particular virus strain is similar to that found in Israel.
Another theory is the virus "escaped" from the Sloan-Kettering Institute where the virus had been provided for experimental treatments.
Over 60 individuals in the New York contacted the disease and seven, all elderly, died.
Within weeks, the disease spread to nearby New Jersey and Connecticut.
Scientists feared that the virus would soon appear in areas to the south of New York based on bird migratory patterns.
Within the first year after discovery in the US the West Nile virus had killed thousands of wild birds from Massachusetts to Maryland.
Controlling the spread of the West Nile virus is dependent upon killing the mosquitoes that can infect with the virus.
Spraying likely mosquito breeding areas is being done in the Northeast with pesticides and larvacides.
Plans are being developed in the southern US for spraying in anticipation of the spread of the virus southward.
