The most famous anabolic steroids use by female athletes was the systematic doping of the East German Olympic teams from 1974 to 1989.
The East German officials and coaches were prosecuted for this doping following the reunification of Germany.
China and the former Soviet Union also used steroids as a governmental policy.
The use of steroids by coaches and individuals, especially professionals, has been seen in many women's sports around the world.
By 1999, teenaged girls in the United States became the fastest growing group of steroid users.
Studies estimated 13% of high school athletes and 2.6% of girls in several middle schools were using the drugs.
The side effects of these drugs are deeper voices, serious acne, excessive hair growth, depression, and aggressiveness.
Some women become sterile and some have children with birth defects.
Side effects also can include heart disease, liver damage including tumors and cancer, and premature death.
One consequence of using these drugs is winning as the East Germans proved, going from 20 medals in the 1972 Olympics to 40 in 1976.
Extensive and complicated testing is employed in an attempt to catch the users.
If caught, individuals and at times teams must forfeit medals, are banned from competition for specific lengths of time, or even are banned from the sport.
To avoid detection, new drugs continually are being developed, some labeled nutritional supplements.
Some nations monitor their own teams to avoid international embarrassment.
By 1999 the quality and rigorousness of Olympic testing was being scrutinized.
