El Nino is a periodic weather phenomenon caused by abnormal warming of the water in the eastern Pacific.
This warming changes the winds and atmospheric pressure, shifting weather patterns and reducing carbon dioxide release.
It can cause storms in California, tornadoes in Florida, a mild winter in the northern states, and reduce the number of Atlantic hurricanes.
It also can cause storms and flooding in South America and Africa, droughts in Indonesia, and flooding in China.
Increased water borne illnesses in Africa and decreased milk production in California have also been attributed to El Ninos.
La Nina is the opposite condition.
There is abnormal cooling of the Pacific sea surface creating a colder, stronger jet stream in the upper atmosphere.
During La Nina the northeast is wet and cold, the southwest is exceptionally dry, and the east is abnormally warm.
There are more tornados and thunderstorms in the mid-west and more hurricanes in the Atlantic.
Northern South America is wet, while the southern part of the continent is dry.
Scientists around the world are trying to understand, track, and predict these phenomena.
NASA satellites measure sea surface temperatures.
The El Nino detection system consists of 70 buoy-borne stations monitoring Pacific winds and waves.
Scientists in the United States, Australia, Israel, and Germany are using sophisticated computer simulations.
Some Chinese are seeking links between El Nino and sunspot cycles.
A 30-foot-long cylinder of mud from a South American lakebed is being analyzed to track the weather cycles back 15,000 years.
