The cause of the crash of EgyptAir Flight 990 off Nantucket in October 1999 may never be known with absolute certainty.
The Boeing 767 was en route from JFK Airport to Egypt.
There were no survivors.
Radar tracks of the flight during its final minutes indicated the plane went into a dive but climbed again before going into an extremely steep dive during which some breaking up of the plane occurred.
The plane's autopilot was disconnected either deliberately or by itself before the plane descended.
One thrust reverser had been previously deactivated because of a problem and there was speculation that a thrust reverser had deployed.
The transponder had also stopped working.
Neither pilot nor co-pilot sent a distress message.
Data from one Black Box showed that both engines had been switched off from the cabin and that the elevators, which raise or lower the plane's nose were in an uneven setting, a move not believed possible for the crew to make.
Cockpit voice recordings indicated that someone uttered a prayer in Arabic just before the autopilot disengaged raising questions of a possible terrorist or suicide act.
The terrorist theory was raised because several Egyptian Army officers were on board.
The plane's copilot had been having problems and had exhibited strange behavior in a New York hotel before the flight suggesting he may have deliberately crashed the plane.
Egyptian authorities discounted the suicide theory and raised the possibility that the plane's problems were caused by electromagnetic interference from military radars.
