EgyptAir Flight 990 crashed on October 31, 1999 after departing JFK Airport.
The plane dropped at near supersonic speed for 9,000 meters, then climbed for 2,400 meters before falling and breaking apart.
There were no radio reports of trouble.
Initial speculation centered on a thrust reverser (deactivated in Cairo).
The flight recorder was recovered on November 9 and revealed that the autopilot was disconnected, the descent appeared "controlled," the cockpit turned off both engines, and the elevators were out of unison.
An on-board computer failure, stopping the transponder and providing erroneous data, was speculated.
A criminal act involving a hijacking, suicide, or a crew fight was also possible and the background, medical history, and emotional stability of the passengers and crew were examined.
The cockpit voice recorder was recovered on November 15.
It contained the co-pilot chanting, "I rely on God" and the pilot ordering actions to control the aircraft.
The National Transportation Safety Board stated on January 21, 2000 that there was no sign of mechanical failure.
Egyptian officials continued to seek other possible causes.
A "triangle of death" over the Atlantic was blamed.
Then "something happened" to the tail.
In August there were rumors that classified radar showed three high-speed returns in the area along the path of the flight.
Several pilots reported seeing fireballs in the area at different times.
The Egyptians continued to blame technical problems, primarily the elevator control system.
In September, a computer shutdown caused by electromagnetic interference from military radars was speculated.
