Violent occurrences and shootings resulting in the deaths of students and teachers in several parts of the country have forced school authorities to implement measures to prevent more tragedy.
Some of these measures are modifications or additions to the school's physical plant such as installing metal detectors and surveillance cameras, keeping most doors locked, removing lockers that could be used to store weaponry, removing things that could provide concealment for a sniper.
Greater involvement with law enforcement officials has led to police officers being assigned to schools.
Some officers are armed and some bring dogs trained to sniff out explosives and the officers sometimes conduct weapons sweeps.
Some schools have implemented a dress code that forbids "gang-type" and baggy clothing that could conceal weapons.
Other schools have mandated use of school uniforms.
Some schools require "see through" book bags and prohibit backpacks.
Identification badges for students, teachers, and visitors are required in some areas.
Schools post signs warning of suspensions for bringing weapons into schools and students who violate the rules do often receive lengthy suspensions.
More schools are beginning to address the root causes of anti-social and violent behavior.
They are promoting friendship and trying to negate rage.
They are instituting programs to bring about conflict resolution and to stop bullying.
In some areas, night sporting events and after school programs have been curtailed.
Hot lines and tip boxes have been established to identify students with problems that could lead to violence.
