Hugo Chavez was elected President of Venezuela in December 1998 and sworn in on February 2, 1999.
He was described as a populist and vowed to root out corruption, subordinate the state oil company to domestic priorities, raise the minimum wage, cut the government payroll, reduce the deficit, and honor the national debt.
His foreign policy was aimed at "peace, integration and defense of human rights".
He wanted Venezuela to play an important role in Latin America, maintain closer ties to Cuba, and continue the one-China policy.
The stock market jumped after his election and the currency strengthened.
Within a year he was able to get a new constitution approved and dissolve the current Congress.
He also began selling government assets to finance social programs.
His election was celebrated with dancing in the streets, but the middle and upper classes were terrified of what he would do.
One critic said he would push the country back into the past.
Investors and businessmen were fearful and within a year almost $4 billion had left the country.
A number of oil executives quit.
External reactions included one diplomat who said that making Congress more representative would give him a good start.
Colombia was not happy with his policy of forcing Colombian truck drivers to turn their vehicles over to Venezuelan drivers at the border.
Several small US oil producers filed a lawsuit.
His prohibition of over flights by US counter-narcotics planes jeopardized the nation's relations with the United States.
