In 1996, China began cracking down on crime.
Extensive investigations and citizen tips led to hundreds of arrests for such crimes as drug trafficking; firearms, ammunition and explosives manufacturing, sales, smuggling and possession; burglary and robbery; murder; hooliganism; kidnapping; racketeering; gambling; and blackmail.
The perpetrators are often gangs of thieves and criminals, and members of international criminal gangs operating between China and Hong Kong or China and Macau.
In 1998, 60% of criminal suspects arrested were minors.
Chinese authorities broke up a Hong Kong-based gang operating between Hong Kong and the mainland.
Its leader was tried, convicted, and sentenced to death in China.
Chinese authorities apprehended members of a Macau gang in its Guangdong Province.
As part of its "Strike Hard national crime-fighting campaign, China agreed to participate in the UN Commission on Crime Prevention and Criminal Justice.
China revised its criminal and procedural laws and enacted new laws.
Its Criminal Law was amended to include terrorist crime, organized crime, money-laundering, illegal immigrant trafficking, and environment-related crimes.
China signed legal assistance agreements with 28 countries and extradition agreements with ten.
China pledged increased cross-border anti-crime cooperation and urged Portugal to take tougher measures against gang-related crime in preparation for the 1999 handover of the Portuguese colony.
After the handover, China will station troops in Macau to better fight organized criminal activity there.
The Chinese government pledges to increase efforts to crack down on corruption, smuggling, and other economic crimes as well as criminal acts in 2000.
