Criminal activity in China in many ways is similar to the crimes committed in other countries.
There are the usual criminal activities of armed robbery, murder, drug-related crimes, illegal firearms, etc. China appears to be most concerned regarding gang-related crimes, kidnapping wealthy persons for ransom and hooliganism.
China crime fighting is complicated by the cross-border crime from Macau and Hong Kong, two jurisdictions soon to come under Chinese control.
Police in Macau arrested three member of the "14K triad" gang who are close to the gang leader, Wan Kuok-koi.
The three are Wong Tat-hou, Wong Wan-wa and Lam Iok-im.
The gang's criminal activity has caused China to want authorities in Macau to clamp down harder on criminal activities.
Members of a gang established by Zeng Qiqiang were arrested for involvement in more than 30 cases of blackmail, gambling, illegal use of guns and other crimes in South China.
Police arrested Cheung Tza-keung and members of his gang who worked out of China but whose crimes were mostly committed in Hong Kong.
Cheung was subsequently tried, convicted and executed in China.
China has intensified its anti-crime activity through the "Strike-Hard" program.
That nation has also signed legal assistance agreements with 28 countries and extradition treaties with ten countries.
