Generation Xers were born from 1965 to as late as 1981.
They are the latchkey children of divorced "baby boomer", into technology, and sharing a worldwide pop culture.
They are described as cautious or brash, independent and isolated yet needy, cynical self-starters who are good with change but distain authority.
By the mid 1990's they were becoming a force in the workplace, at times in conflict with the older workers.
Although both groups wanted the same general managerial environment, the Gen Xers demanded it.
They needed different training and frequent feedback and expected to change jobs often.
They were delaying marriage and women began to feel they didn't want everything like their mothers had.
Babies were the new status symbol.
Gen Xers feared rising taxes to support the aging boomers.
They were beginning to save for retirement early, but choosing conservative investments.
They found politics boring and generally didn't align with political parties.
They were more likely to volunteer than vote.
Some continued to join the Peace Corps and the wealthier were getting into philanthropy.
Their suspicions of institutions carried over churches, but some clergy considered them spiritual and the Dalai Lama and Pope John Paul II were popular.
In the market, they wanted digital video recorders and cameras, online money, and retro fashions from Goodwill.
Most preferred foreign smaller automobiles such as the Honda Civic, but automakers were in hot pursuit with Neons, PT Cruisers, and the Xterra.
Vintners were hoping to change their taste from Margaritas to wine.
