Ex-President Jimmy Carter has been a champion for world peace and human rights since leaving office.
He has met with various dictators, including Yasser Arafat, Kim Il-sung, and Daniel Ortega, to plead the case for peace and obtain the release of some 50,000 political prisoners.
In addition, he and his wife, Rosalynn, established the Carter Center in 1982.
This center is focused on efforts to ensure free elections and fight several third world diseases.
Delegations from the Carter Center, frequently led by President Carter, have observed and evaluated elections all around the world.
Elections have been observed in at least 10 Central and South American countries, including Mexico, Panama, and Peru.
In 1998 the Center initiated a project called "Transparency for Growth in the Americas".
The Center's delegations have observed elections in China (where Carter fosters his one-China policy), Indonesia, Nigeria, Liberia, and Mozambique.
Since 1987 the Center has been committed to the eradication of river blindness in Africa.
This disease is caused by black flies and 18 million people were infected by 1999.
The Center is also fighting Guinea-worm disease in Africa and Asia.
In 1986 an estimated 3 million people were infested each year with this roundworm.
In 2000 the Center recognized Pakistan for being the first Asian nation to eradicate the disease.
In 1999, the Center initiated its first program aimed at eradicating trachoma, another eye disease caused by black flies, which has blinded 6 million people and infected millions more.
