Former President Jimmy Carter has played an active role on the international stage.
Working in conjunction with the Carter Center that he founded and the National Democratic Institute of International Affairs, Carter has led many international teams of observers to monitor elections throughout the world.
By 1999 he had monitored more than 20 elections in 16 countries including Nicaragua, Liberia, Nigeria, Venezuela, China (village and township committee elections), Indonesia, Mozambique, Peru, the Dominican Republic and Mexico.
Carter has visited 115 countries to promote peace and human rights or to combat disease and hunger.
He is credited with gaining release of approximately 50,000 political prisoners, not hesitating to meet personally with such leaders as Yasser Arafat, Kim-Il-Sung, Daniel Ortega, Haitian bully Raoal Cedras and Bosnian Serb Radovan Karadzic.
In 1998 the Carter Center devoted a $1.5 million grant from Coca-Cola to "Transparency for Growth in The Americas," a program for combating corruption through openness in government.
Through the Carter Center, the former President has led successful campaigns against two devastating diseases: river blindness and Guineau worm disease.
In 1999 the Center received grants totaling $30 million to expand programs for treatment and prevention of blindness in Africa and Latin America and to extend its anti-trachoma program from Mali to Sudan, Ethiopia, Nigeria, Niger, Ghana and Yemen.
In August 1999 President Clinton awarded former President Carter the Medal of Freedom for his successes in the struggle for peace and human rights and against disease and hunger.
