The decline of salmon populations off the Pacific coasts of the United States and Canada is one of the 20th century's environmental disasters.
In 1999, the federal government acting under the Endangered Species Act set in motion a regional plan to restore salmon runs in the Pacific Northwest.
The US and Canada announced a plan to limit salmon catches and establish a fund to protect the fish.
Prior to this agreement, the two countries were at odds on salmon fishing.
Canada had accused the US of failing to honor the Pacific Salmon Treaty of 1985 by over fishing.
Also, the Canadian Province British Columbia attempted to sue the US Government for over fishing.
Operators of three Columbia River dams have agreed with the Clinton administration on a 50-year preservation plan for saving salmon.
The major requirement is that the dams be operated with no net loss of salmon.
Dams in several parts of the Northwest are to be made more fish friendly and measurers are being taken to thwart predators like seagulls and squawfish from feasting on immature salmon.
Catch limits will be imposed and prosecutions will be undertaken against the most egregious toxic chemicals dumping in rivers and streams.
However, experts agree that the most effective remedy for the salmon's plight is the breaching of dams on spawning rivers.
Some dams in California will be removed by 2001.
That state also negotiated a habitat conservation plan with Pacific Lumber to stop logging adjacent to streams when coho salmon spawn.
