In negotiating labor agreements between the major US automobile manufacturers and the United Auto Workers, the principal issue on the part of the UAW is job security.
The automakers seek labor contracts that would allow them to increase productivity that, they say, is hampered by union work rules and union opposition to outsourcing.
General Motors and Ford would both like to spin off their parts divisions, Delphi and Visteon, respectively, into separate companies which would have different labor agreements.
The UAW contends that GM has reneged on a pledge to modernize and has ignored health and safety grievances.
The UAW says that GM is spending billions of dollars on factories in developing countries and failing to invest at home.
GM counters that the majority of its investments are in the US but for car-building operations only and not for its parts division.
GM contends that the quota system in effect at Delphi results in employees being paid for eight hours work when often a worker accomplishes the task in four to six hours.
The future of parts workers remains a key issue at both GM and Ford.
Replacement of retiring workers is also an issue for DaimlerChrylser as well as at GM and Ford.
Wages and benefits continue to be an issue between the UAW and the big three automakers.
