The key issues between the United Auto Workers (UAW) and the three largest automakers - General Motors (GM), Ford Motor Company, and Daimler Chrysler - have traditionally focused on demands for job security, health care costs, overtime pay, compensation, investments, and downsizing.
When the UAW feels these demands are utmost, they generally respond by workers' strikes.
The automobile executives, especially at GM, have vowed to proceed with a long-standing plan to keep costs down, invest heavily in new models and technology, simplify building and selling of vehicles, and to cope with non-U.S.
competitors. This plan concerns the UAW because it is causing a decline in high payday assembly jobs as industry becomes more efficient and needs fewer workers.
The most contentious labor issue is outsourcing, which at GM and Ford involves "spinning off" auto parts divisions, the purchasing of pre-assembled module parts from outside suppliers, investment in assembly plants overseas, while not investing in aging American factories.
A strike in 1998 over the downgrading of two parts factories in Flint, Michigan shut down GM's North American production at a loss of $2 billion in revenue.
With record sales and profits now at all three automakers, both sides are eager to avoid strikes.
This enabled the UAW to craft contracts with the automakers providing workers with 3% raises each year for four years, a signing bonus of $1,350, and improvements in pensions and cost-of-living adjustments.
The issue of "spin-off" could become contentious if it leads to shedding workers or lowering pay.
