There is not enough low-cost housing in the United States.
In 1995 there were 4.4 million more low-income earners than there were low-cost housing units and the pool of affordable housing was shrinking.
Landlords were dropping out of rent subsidy programs to raise the rent or convert the real estate to condominiums.
The number of homeless was rising.
In addition, rents were going up faster than incomes.
In 1997 at least 4.5 million families were paying more than 50% of their income on housing, up 12% since 1991.
To address this crisis, various programs were used to create more low-cost housing.
Tax credits were created to encourage builders to build more units and build in low-income areas.
Grants were made to non-profit organizations to build or rehabilitate apartments for the elderly and disabled.
One jurisdiction was granting builders greater density construction for reserving a percentage of units to rent below market value.
Local governments can seize abandoned houses to convert to affordable homes.
More money was allocated to subsidize landlords who rent below market value.
Real estate investment trusts were being formed that specialized in affordable housing.
More money must also be made available to the poor.
The number of rent vouchers given to low-income city dwellers was increased.
Using these vouchers to buy a home became possible in 2000.
Special low-interest loans were to be made available to low-income and minority individuals.
The dollar limit of federally insured mortgages was raised.
Raising the minimum wage also was proposed.
