The Russian Oscar II-class, atomic powered submarine, the Kursk, sank in the Barents Sea on August 12, 2000 during a naval exercise.
The boat, one of Russia's largest, was commissioned in 1996 and carried a crew of 118.
The Russians began a massive rescue effort on August 13 and announced the loss the next day, when 15 vessels and warships were involved in the search.
Russian efforts to reach the submarine using underwater capsules failed and Russia talked to NATO officials.
Russia turned down a French offer of help and Germany's offer of medical specialists.
On August 16, Russia asked Britain and Norway to send a rescue submarine and divers.
These rescue teams arrived at the scene on August 19 and began the descent to the Kursk on the 20th.
The Russians confirmed all aboard were dead on the 21st.
Various causes of the disaster were presented.
The United States believed one of the Kursk's torpedoes misfired causing a massive explosion.
Russian officials speculated that the Kursk collided with another vessel, probably a foreign submarine, or encountered a World War II mine.
One German source said a Russian anti-submarine missile hit it.
Putin vowed to retrieve the bodies of the crew and the vessel itself.
Plans were made for an unnamed Norwegian company to begin the body retrieval operation on October 10.
The Russians hoped to raise the boat in the summer of 2001 at an anticipated cost of $45 million.
