On August 19, 2000, a Russian nuclear submarine with 118 men aboard sank to the bottom of the Barents Sea while on a training mission.
Initial reports indicated that the ship may have been involved in a collision or could have been damaged by an explosion.
The ship was reported not to be carrying nuclear weapons and its nuclear reactor had been switched off.
Russian navy rescue efforts were complicated by strong underwater currents and near zero visibility at the 450 feet depth where the vessel was trapped and by heavy surface storms.
Examination with deep-water apparatus indicated it could have been shattered by a blast in its bow, which caused the torpedo section to fill with water.
The condition of the crew could not be determined and efforts to hook air and fuel lines failed.
By the seventh day, repeated attempts to dock with an escape hatch failed and Russian officials were virtually certain that all the crew were dead.
After initially refusing Western aid, the Russians agreed to accept rescue submarines and divers from Britain and Norway.
Norwegian divers descended with video equipment, surveyed the damage, and ultimately opened an inner hatch, which revealed heavy flooding.
A British mini-submarine was unable to dock with an escape hatch.
US sonar and other technical sources clearly provided no evidence of a collision.
The Russians, who ultimately signed a contract with Dutch and Belgian companies to retrieve the submarine, continued to insist throughout that the sinking was caused by a collision.
