The fundamental principle of Mongolia's foreign policy, according to the Minister of External Relations, is that the country should be active in political and economic activities in northeast Asia and the whole Asian-Pacific region.
Mongolia's relationship with bordering neighbors China and Russia must be maintained at an appropriate level.
Sino-Mongolian relations were normalized in 1989, and since then the two countries have worked to strengthen ties and develop economic and trade cooperation in the interest of regional peace and stability.
China supports Mongolia as a nuclear-free zone.
China pledges to abide by the principles of peaceful co-existence and the treaty on Sino-Mongolian friendship and cooperation.
Russia has stated that economic and trade problems between Russia and Mongolia will be resolved and that there are no major conflicts between the two countries.
Mongolia is in the process of transforming from a central-planning economy to a market oriented-economy and requires technical and monetary aid for the restructuring and to help improve the living conditions of the country's poor.
Mongolia ranks among the five most foreign assisted countries of the world.
Japan is the main provider of aid to Mongolia.
Aid also comes from the US, China, European countries (Britain, France, Denmark and Germany), Canada, Kuwait and from the World Bank, United Nations and the Asian Development Bank.
Mongolia decided to apply to join the World Trade Organization and the Asia-Pacific Economic Cooperation forum.
