During five and a half years of George W. Bush's tenure as governor, Texas executed 143 prisoners on death row, far more than any other state during modern times.
Women, juveniles, and mentally deficient were among those executed.
Bush has repeatedly said that he reviews each case for any doubt of the condemned's guilt.
In only one case has Bush granted a 30-day reprieve and told the parole board to review the case so DNA tests could be pursued.
By law a Texas governor cannot halt an execution unless the Texas Board of Pardons and Paroles first recommends a reprieve, commutation to a life sentence or a pardon.
He can veto a board vote on those recommendations.
He cannot overrule a board vote to proceed with an execution.
The Board was appointed by Governor Bush and is believed to share his views on capital punishment.
Governor Bush vetoed a bill to establish a state public defender system.
Lacking such a system many indigent defendants were poorly defended according to a study published in the Chicago Tribune.
Bush responded that the defendants had full access to a fair trial.
Amnesty International claims Texas' secretive clemency process for condemned criminals violates minimum safeguards for human rights.
The Canadian Foreign Minister contended that sentencing a Canadian to death row violated an international treaty.
The death sentence of Karla Faye Tucker brought pleas for clemency from Pope John Paul II and from Christian broadcaster Pat Robertson because of Tucker's death row conversion to Christianity.
