Empta is a precursor for production of the deadly nerve gas VX.
Traces of Empta were found near a Ugandan pharmaceutical plant in 1998.
The US bombed this plant because of Sudan's ties to Iraq and Osama bin Laden.
Although some research papers discuss using this Empta to produce anti-microbial agents, there is no known industrial use.
A Milwaukee plant produces some for research.
Other VX precursors are phosphorous trichloride, phosphorous pentasulfide, and diisopropyl ethylamine.
VX itself probably existed in the US, Russia, Iran, Syria, and Iraq.
It was used by a Japanese cult in a 1994 attack and in 1998 was found on Iraqi warheads at a weapons demolition site.
Tons of CP3POC12, a precursor to Sarin and other nerve agents, were taken from a production facility in Bosnia in 1992.
The former Yugoslavia had weaponized CS, Sarin, and BZ.
These weapons probably ended up in Serbian hands and BZ may have been used in Kosovo.
The Chemical Weapons Treaty governs chemical weapons.
Schedule 1 items only kill people and are prohibited.
Schedule 2 items are subject to inspections.
Four hundred people are involved with these inspections, which include camera surveillance.
Any suspected materials are to be destroyed and the destruction is monitored.
Sanctions are levied on violators and NATO attacks are possible.
Individual governments also ban shipment of dual-use chemicals.
US and the former Soviet Union had vast stores of chemical weapons.
The US is destroying its at incinerators in Tooele, Utah and Johnston Island in the Pacific.
