In the mid and late 1990s there was a marked decrease in both violent and non-violent crimes in the United States.
Percentage drops, many in the double digits, were recorded for murders, rapes, burglaries, personal theft, vehicle theft, purse snatching and property theft.
The greatest decrease was in the Northeast followed by the West, South, and Midwest.
The extent of the decrease in murders is illustrated by Chicago being named the murder capital of the US in 1999 after a ten-year low in number of murders.
Detroit showed an increase in murders in 1999 but other crimes declined.
Crime rates were not always uniform in any of the regions.
New York experienced a huge drop in the number of murders but some counties in New York State saw an increase.
In California, some regions near Los Angeles had a decrease in crime and others nearby had an increase.
In Richmond, Virginia, gun-related crimes decreased by stringent law enforcement under Project Exile.
Arrests for drug crimes did increase throughout the country.
New Orleans had the nation's worst murder rate in 1994; then the rate there decreased until 2000 when it saw a big jump.
New Orleans was not alone that year in having an increase in number of murders.
Baltimore, Boston, Dallas, Los Angeles, New York and Philadelphia also showed an increase in that year.
Two other large cities, Denver and Phoenix showed a decrease in their number of murders in 2000.
