Attention Deficit Disorder (ADD) and Attention Deficit Hyperactive Disorder (ADHD) are neurological and genetic disorders that are evident in childhood and continue through adulthood.
Onset of ADHD does not occur in adulthood except through trauma.
Girls have Type A, characterized by inattentiveness and distractibility; boys have type B and are hyperactive and impulsive.
It is estimated that from three to five or even nine percent of children have the disorder, which twenty percent may outgrow.
ADD/ADHD is diagnosed through behavioral patterns but many of those afflicted have been found to have a high concentration of a key brain protein, a dopamine transporter, which could lead to a clinical diagnosis.
A clinic associated with the University of Tennessee claims a test involving monitoring the front region of the brain is 90% effective in diagnosis.
An increase in the number of diagnoses of ADHD is attributed to include either hyperactivity or impulsive behavior but not necessarily both.
The drug Ritalin is the most widely prescribed medication to control behavior of ADD/ADHD.
The drug Adderall is used to a lesser extent and even Prozac has been prescribed.
Use of those drugs to treat ADD/ADHD is highly controversial.
Critics say that doctors are too quick to diagnose ADHD and over-prescribe drugs for children.
Ritalin has side effects including sleeplessness and loss of appetite.
Its use controls behavior, but not drug has been yet found to treat the disorder.
