The "Stars Wars Episode I--the Phantom Menace"-mania began in 1997 with the re-release of the Star Wars Trilogy.
The first trailer of the "Phantom Menace" was screened in November 1989, becoming an unprecedented film event.
The movie's second trailer went online in March 1999 with one million downloads in one day.
The Internet had hundreds of Star Wars-related sites.
Hasbro Inc., Galoob Toys, Inc., and Lego were manufacturing goods including a countdown clock for the May 17 release.
Pepsi, Taco Bell, Pizza Hut, Kentucky Fried Chicken, and Pez Candy Dispensers planned promotions.
The media--from "60 Minutes" to the New York Times to Vogue--were running features and creating press packages.
On April 30, 40,000 fans attended a LucasfilmLTD-sanctioned "Star Wars Celebration" in Denver.
Stores had special hours to accommodate the release of merchandise on May 2.
Wal-Mart had Star Wars-related goods in 16 of its 36 departments.
Sales were expected to reach $2 billion.
Fans began lining up at theaters on May 3.
Cheering mobs greeted the film as it finally opened, but reviews were mixed with the movie praised for its special effects and computer generated scenes.
It brought in $100 million in 5 days, and $200 million in 13.
Some Europeans and Japanese flew to America for the opening and pirated copies were in Hong Kong in a week.
The Asian version opened on July 10 to the joy of the Japanese fans, but an anticipated craze in the United Kingdom did not materialize.
