In the late 1990's some governments were moving toward banning smoking in smokers' last havens--restaurants and bars, while other nations had yet to ban smoking in hospitals.
Acknowledged health hazards were the primary reason to ban smoking, including the cost of health care.
Reasons not to support laws included that they violated individual and free-trade rights, governments lost revenues from tobacco sales, bars and restaurants would lose business, and bans did not decrease smoking or stop teens from starting.
Non-compliance and non-enforcement were rampant.
In the United States, earlier workplace bans were expanding to include bars and restaurants in California, New York, and New Jersey.
The same expansion was occurring in Canada and Australia.
In Latin America, smoking generally was banned in hospitals, theaters, and transportation facilities.
In Europe, bans ranged from none in Portugal to every public place but pubs in England.
Israel was on par with the United States, but other mid-East countries either had no laws--especially tobacco growing countries, or did not enforce them.
South Africa enacted tough laws in 1998, with no smoking in public areas outside designated smoking zones.
In 1996 Chinese provincial and local governments began enacting bans on smoking in public places, but they were generally ignored.
Macao and Thailand banned smoking in some public places.
Japan had few laws even protecting public transportation.
Singapore had been enacted increasingly restrictive laws since 1970.
By 1998, smoking was allowed only in selected bars and outdoors; 18% of the people still smoked.
