Increasingly, the nations of the world are enacting laws to ban or restrict smoking in certain areas, mostly in public places such as hospitals, schools, stores, and transportations systems.
Many of the laws allow exceptions for well-ventilated areas of bars and cafes.
In some countries, especially in Western Europe anti-smoking laws have been enacted but are not enforced and are mostly ignored.
Some countries, such as Germany have voted down proposed anti-smoking legislation.
Singapore has legislation that would make the entire country non-smoking.
In China, anti-smoking bans have been decreed in the major cities but have not been followed in towns in lesser-populated areas.
In the US, the GOP-dominated Senate voted down sweeping anti-smoking legislation but encouraged states to punish minors who smoke.
The New Jersey governor vetoed a bill that would have punished underage smokers but several towns in that state have enacted smoking bans.
Within the US, California has the strictest anti-smoking rules.
Opposition to anti-smoking bans is mostly from restaurant and bar owners who claim they will lose business if smoking is not allowed.
However, not all restaurant owners share that view.
Anti-smoking opponents in South Africa may attempt to challenge smoking bans on constitutional grounds.
Anti-smoking elements in Jordan claim that economic and health costs far outweigh revenues from domestic tobacco production and imports.
